// GENERATED by packages/extract/build.mjs. DO NOT EDIT BY HAND.
// ESM copy of @edit/extract for import from the popup (module context).
// Source of truth: packages/extract/{index,rules}.js

// @edit/extract — canonical product extraction.
//
// Pure and DOM-adapter based: every function takes an explicit `doc`
// (a Document) and `loc` ({ href, hostname }) instead of touching the
// browser `document`/`location` globals. This lets the exact same code
// run under jsdom in unit tests AND, after inlining, inside the extension
// content script (see packages/extract/build.mjs).
//
// Extraction priority (kept in sync with the handoff brief §4):
//   name:     JSON-LD Product.name -> og:title -> document.title
//   price:    JSON-LD offers.price/lowPrice -> product:price:amount
//             -> og:price:amount -> DOM heuristic
//   currency: JSON-LD priceCurrency -> product:price:currency
//             -> og:price:currency
//   image:    JSON-LD image -> og:image -> biggest <img>
//   brand:    JSON-LD brand.name -> product:brand
//   site:     og:site_name -> domain-derived
//
// A domain-rule layer (see applyRules) runs after the generic pass so
// curated per-site rules can fill or override fields on sites whose
// structured data is thin.

export function jsonLdProducts(doc) {
  const out = [];
  const nodes = doc.querySelectorAll('script[type="application/ld+json"]');
  nodes.forEach((n) => {
    let data;
    try { data = JSON.parse(n.textContent); } catch { return; }
    const stack = Array.isArray(data) ? [...data] : [data];
    while (stack.length) {
      const o = stack.pop();
      if (!o || typeof o !== "object") continue;
      if (Array.isArray(o["@graph"])) stack.push(...o["@graph"]);
      const t = o["@type"];
      const isProduct = t === "Product" || (Array.isArray(t) && t.includes("Product"));
      if (isProduct) out.push(o);
    }
  });
  return out;
}

export function metaContent(doc, sel) {
  const el = doc.querySelector(sel);
  return el ? (el.getAttribute("content") || "").trim() : "";
}

export function firstOffer(prod) {
  let off = prod.offers;
  if (Array.isArray(off)) off = off[0];
  if (off && off["@type"] === "AggregateOffer") return off;
  return off || null;
}

export function pickPriceFromDom(doc) {
  // last-resort heuristic: find a visible price-like number
  const sel = '[itemprop="price"],[class*="price" i],[class*="Price" i],[id*="price" i]';
  const els = Array.from(doc.querySelectorAll(sel)).slice(0, 40);
  for (const el of els) {
    const txt = (el.getAttribute("content") || el.textContent || "").trim();
    const m = txt.replace(/,/g, "").match(/(?:¥|\$|€|£|￥)?\s*([0-9]{2,9}(?:\.[0-9]{1,2})?)/);
    if (m && Number(m[1]) >= 100) return m[1];
  }
  return "";
}

// Resolve a possibly relative / protocol-relative URL against the page.
export function absUrl(u, base) {
  if (!u) return "";
  try { return new URL(u, base).href; } catch { return u; }
}

// Resolve the best URL for an <img>, tolerating lazy-loading patterns.
function imgSrc(img) {
  const direct = img.currentSrc || img.getAttribute("src") ||
    img.getAttribute("data-src") || img.getAttribute("data-original") ||
    img.getAttribute("data-lazy-src") || img.getAttribute("data-image") || "";
  if (/^https?:/.test(direct)) return direct;
  const ss = img.getAttribute("srcset") || img.getAttribute("data-srcset") || "";
  if (ss) {
    const urls = ss.split(",").map((s) => s.trim().split(/\s+/)[0]).filter((u) => /^https?:/.test(u));
    if (urls.length) return urls[urls.length - 1]; // usually the largest
  }
  return "";
}

export function biggestImage(doc) {
  let best = "", area = 0, lazyFallback = "";
  doc.querySelectorAll("img").forEach((img) => {
    const src = imgSrc(img);
    if (!src) return;
    const a = (img.naturalWidth || img.width || 0) * (img.naturalHeight || img.height || 0);
    if (a > area) { area = a; best = src; }
    if (!lazyFallback && !/sprite|icon|logo|blank|placeholder|1x1/i.test(src)) lazyFallback = src;
  });
  // Prefer a properly-sized image; otherwise a plausible lazy one (area 0).
  return area > 40000 ? best : (lazyFallback || best);
}

// ---- Shopify enrichment ----------------------------------------------------
// Many brand-official stores run Shopify but ship thin page metadata (no
// og:image / JSON-LD). Shopify exposes clean product JSON at `<product-url>.js`,
// which these helpers turn into our item shape. The fetch itself happens in the
// content script (same-origin) or the popup re-check; these stay pure/testable.

// Build the `<product>.js` URL from a product page URL, or "" if not a product.
export function shopifyProductJsonUrl(href) {
  try {
    const u = new URL(href);
    // Shopify product URLs are exactly /products/<handle> (handle = last segment).
    // Excludes /products/detail/123 (EC-CUBE etc.) which is NOT Shopify.
    const m = u.pathname.match(/^(.*\/products\/[^/?#]+)\/?$/);
    return m ? u.origin + m[1] + ".js" : "";
  } catch { return ""; }
}


// Pull the size list from a Shopify product's options/variants.
export function shopifySizes(p) {
  const opts = Array.isArray(p && p.options) ? p.options : [];
  let sizeIdx = -1, values = [];
  opts.forEach((o, i) => {
    const name = typeof o === "string" ? o : (o && o.name) || "";
    if (/size|サイズ|size|寸/i.test(name)) { sizeIdx = i; if (o && Array.isArray(o.values)) values = o.values.slice(); }
  });
  if (values.length) return values.join(", ");
  const variants = Array.isArray(p && p.variants) ? p.variants : [];
  if (sizeIdx >= 0 && variants.length) {
    const key = "option" + (sizeIdx + 1);
    const set = [...new Set(variants.map((v) => v && v[key]).filter(Boolean))];
    if (set.length) return set.join(", ");
  }
  if (opts.length === 1 && variants.length) { // single-option product: use variant titles
    const set = [...new Set(variants.map((v) => v && (v.option1 || v.title)).filter((t) => t && t !== "Default Title"))];
    if (set.length) return set.join(", ");
  }
  return "";
}

// Available colors from a Shopify product's Color/カラー/色 option.
export function shopifyColors(p) {
  const opts = Array.isArray(p && p.options) ? p.options : [];
  for (let i = 0; i < opts.length; i++) {
    const o = opts[i];
    const name = typeof o === "string" ? o : (o && o.name) || "";
    if (/colou?r|カラー|色/i.test(name)) {
      if (o && Array.isArray(o.values)) return [...new Set(o.values)].join(", ");
      const variants = Array.isArray(p.variants) ? p.variants : [];
      const set = [...new Set(variants.map((v) => v && v["option" + (i + 1)]).filter(Boolean))];
      if (set.length) return set.join(", ");
    }
  }
  return "";
}

// Per-size availability from a Shopify product's variants (stock differs by size).
// Returns { "M": "instock", "L": "outofstock", … }.
export function shopifyAvailBySize(p) {
  const opts = Array.isArray(p && p.options) ? p.options : [];
  let sizeIdx = -1;
  opts.forEach((o, i) => { const name = typeof o === "string" ? o : (o && o.name) || ""; if (/size|サイズ|寸/i.test(name)) sizeIdx = i; });
  const variants = Array.isArray(p && p.variants) ? p.variants : [];
  const out = {};
  const mark = (s, v) => { const k = String(s || "").trim(); if (!k || k === "Default Title") return; out[k] = v && v.available === false ? "outofstock" : "instock"; };
  if (sizeIdx >= 0) { const key = "option" + (sizeIdx + 1); variants.forEach((v) => mark(v && v[key], v)); }
  else if (opts.length === 1) { variants.forEach((v) => mark(v && (v.option1 || v.title), v)); }
  return out;
}

// Map a parsed Shopify product-JSON object to a partial item.
export function shopifyFromJson(p, opts = {}) {
  if (!p || typeof p !== "object") return null;
  const code = String(opts.currency || "").toUpperCase();
  // Shopify's AJAX (.js) price is ALWAYS integer × 100 — even for JPY
  // (verified: LEMAIRE €590→59000, kindal ¥198,550→19855000). Always /100.
  const img = p.featured_image || (Array.isArray(p.images) && p.images[0]) || "";
  return {
    name: p.title ? String(p.title) : "",
    brand: p.vendor ? String(p.vendor) : "",
    price: p.price != null && !isNaN(Number(p.price)) ? String(Math.round(Number(p.price) / 100)) : "",
    currency: code,
    image: img ? absUrl(img, opts.href || "") : "",
    availability: p.available === true ? "instock" : (p.available === false ? "outofstock" : ""),
    sizes: shopifySizes(p),
    colors: shopifyColors(p),
    availBySize: shopifyAvailBySize(p),
  };
}

// Keyword-based category guess (大カテゴリ/中カテゴリ) from free text.
const CATEGORY_KEYWORDS = [
  ["トップス", "コート", /コート|coat/i],
  ["トップス", "ジャケット", /ジャケット|ブルゾン|アウター|jacket|blouson|outer/i],
  ["トップス", "シャツ", /シャツ|ブラウス|shirt|blouse/i],
  ["トップス", "Tシャツ", /t\s?シャツ|tシャツ|カットソー|ティーシャツ|t-?shirt|tee|cut\s?and\s?sewn/i],
  ["トップス", "ノースリーブ", /ノースリーブ|タンク|キャミ|sleeveless|tank/i],
  ["トップス", "ニット", /ニット|セーター|カーディガン|プルオーバー|knit|sweater|cardigan/i],
  ["ボトムス", "ハーフパンツ", /ハーフパンツ|ショートパンツ|ショーツ|short/i],
  ["ボトムス", "パンツ", /パンツ|スラックス|デニム|ジーンズ|トラウザー|チノ|pants|trouser|denim|jeans|slacks/i],
  ["ボトムス", "スカート", /スカート|skirt/i],
  ["ワンピース", "", /ワンピース|ドレス|dress|one\s?piece/i],
  ["靴", "スニーカー", /スニーカー|sneaker|trainer/i],
  ["靴", "ブーツ", /ブーツ|boots?/i],
  ["靴", "パンプス", /パンプス|pumps|heel/i],
  ["靴", "サンダル", /サンダル|sandal/i],
  ["靴", "", /シューズ|くつ|靴|shoe|loafer|ローファー/i],
  ["アクセサリー", "バッグ", /バッグ|トート|リュック|ショルダー|ハンドバッグ|クラッチ|bag|tote|backpack/i],
  ["アクセサリー", "帽子", /帽子|キャップ|ハット|ニット帽|cap|hat|beanie/i],
  ["アクセサリー", "ジュエリー", /ネックレス|リング|ピアス|イヤリング|ブレスレット|ジュエリー|necklace|ring|earring|bracelet|jewel/i],
  ["アクセサリー", "ベルト", /ベルト|belt/i],
];

export function guessCategory(text) {
  // strip zero-width / invisible chars (some sites inject them, breaking「シャツ」etc.)
  const t = String(text || "").replace(/[​‌‍⁠﻿­]/g, "");
  if (!t.trim()) return { major: "", sub: "" };
  for (const [major, sub, re] of CATEGORY_KEYWORDS) {
    if (re.test(t)) return { major, sub };
  }
  return { major: "", sub: "" };
}

export function domainToSite(domain) {
  const parts = String(domain || "").split(".");
  const core = parts.length >= 2 ? parts[parts.length - 2] : parts[0];
  return core ? core.charAt(0).toUpperCase() + core.slice(1) : "";
}

// Normalize a schema.org / OG availability value into a small vocabulary:
// "instock" | "outofstock" | "preorder" | "" (unknown).
export function normAvailability(v) {
  if (!v) return "";
  const s = String(v).toLowerCase();
  if (/(outofstock|soldout|out of stock|discontinued)/.test(s)) return "outofstock";
  if (/(preorder|backorder)/.test(s)) return "preorder";
  if (/(instock|in stock|onlineonly|instoreonly|limitedavailability|available)/.test(s)) return "instock";
  return "";
}

// Best-effort size extraction from a JSON-LD Product. Handles a bare
// `size`, an array of sizes, and `hasVariant[].size`. Returns a
// comma-joined string (may be "").
export function sizesFromProduct(p) {
  const acc = [];
  const push = (v) => {
    if (!v) return;
    if (Array.isArray(v)) v.forEach(push);
    else if (typeof v === "object") push(v.name || v.value);
    else acc.push(String(v).trim());
  };
  push(p && p.size);
  if (Array.isArray(p && p.hasVariant)) p.hasVariant.forEach((vr) => push(vr && vr.size));
  return Array.from(new Set(acc.filter(Boolean))).join(", ");
}

// Heuristic: pull size options from the page DOM (for non-Shopify stores like
// ARKnets where sizes live in a <select> or a group of size buttons, not in
// structured data). Conservative to avoid grabbing non-size selects.
export function looksLikeSize(t) {
  return /^(x{0,3}s|s|m|l|xl|xxl|xxxl|ll|3l|4l|free|f|フリー|ワンサイズ|\d{1,3}(?:\.\d)?)$/i.test(String(t || "").trim());
}
// Extract a leading size token from text like "L（在庫わずか）" or "2 予約可能".
export function leadingSize(t) {
  const m = String(t || "").trim().match(/^(x{0,3}s|s|m|l|xl|xxl|xxxl|ll|3l|4l|free|f|フリー|ワンサイズ|\d{1,3}(?:\.\d)?)\b/i);
  if (!m) return "";
  if (/^\d/.test(m[1])) { const n = Number(m[1]); if (n < 1 || n > 60) return ""; } // numeric sizes only in a sane range
  return m[1];
}
export function sizesFromDom(doc) {
  const clean = (t) => String(t || "").split(/[（(]/)[0].replace(/\s*(在庫|残り|わずか|×|✕|sold\s*out|完売).*$/i, "").trim();
  // (a) a <select> that is (or contains) a size chooser
  for (const s of doc.querySelectorAll("select")) {
    const hint = ((s.getAttribute("name") || "") + " " + (s.id || "") + " " + (s.getAttribute("aria-label") || "") + " " + (s.className || "")).toLowerCase();
    const opts = Array.from(s.options || []).map((o) => clean(o.textContent))
      .filter((t) => t && !/^(選択|お選び|選ぶ|please|choose|select|size|サイズ|-{1,2}|―)/i.test(t));
    if (!opts.length) continue;
    if (/size|サイズ/.test(hint) || opts.every(looksLikeSize)) {
      const uniq = [...new Set(opts)].filter(Boolean);
      if (uniq.length) return uniq.join(", ");
    }
  }
  // (b) size-hinted elements whose (short) text starts with a size token —
  // covers <select>-less stores (ARKnets: <div class="...variation-size">2 予約可能</div>)
  const found = [];
  for (const g of doc.querySelectorAll('[class*="size" i],[id*="size" i]')) {
    const t = (g.textContent || "").trim();
    if (!t || t.length > 24) continue; // skip wrappers / size-guide blurbs
    const s = leadingSize(t);
    if (s) found.push(s.toUpperCase());
  }
  if (found.length) return [...new Set(found)].join(", ");
  return "";
}

// Parse a product size/measurement table (実寸表) into per-size measurements.
// Returns { bySize: { "M": {肩幅:"55",...} }, order: ["XS",...] } or null.
const MEASURE_HEADER_MAP = {
  "肩幅": "肩幅", "身幅": "身幅", "着丈": "着丈", "総丈": "着丈", "袖丈": "袖丈", "裄丈": "袖丈",
  "ウエスト": "ウエスト", "ウェスト": "ウエスト", "股上": "股上", "股下": "股下",
  "わたり": "わたり幅", "わたり幅": "わたり幅", "もも幅": "わたり幅", "裾幅": "裾幅",
};
export function measuresFromTable(doc) {
  const known = Object.keys(MEASURE_HEADER_MAP);
  for (const table of doc.querySelectorAll("table")) {
    const rows = Array.from(table.querySelectorAll("tr"))
      .map((tr) => Array.from(tr.querySelectorAll("th,td")).map((c) => (c.textContent || "").trim()));
    if (rows.length < 2) continue;
    let hi = -1;
    for (let i = 0; i < rows.length; i++) {
      if (rows[i].filter((x) => known.some((k) => x.includes(k))).length >= 2) { hi = i; break; }
    }
    if (hi < 0) continue;
    const header = rows[hi];
    const colField = {};
    header.forEach((h, idx) => { const k = known.find((kk) => h.includes(kk)); if (k) colField[idx] = MEASURE_HEADER_MAP[k]; });
    if (!Object.keys(colField).length) continue;
    let sizeCol = header.findIndex((h) => /サイズ|size/i.test(h));
    if (sizeCol < 0) sizeCol = 0;
    const bySize = {}, order = [];
    for (let i = hi + 1; i < rows.length; i++) {
      const r = rows[i];
      const size = (r[sizeCol] || "").trim();
      if (!size || /単位|cm|inch|備考/i.test(size)) continue;
      const m = {};
      for (const idx of Object.keys(colField)) {
        const v = (r[idx] || "").replace(/[^0-9.]/g, ""); // size-chart values are already in cm
        if (v && !isNaN(Number(v))) m[colField[idx]] = v;
      }
      if (Object.keys(m).length) { bySize[size] = m; order.push(size); }
    }
    if (order.length) return { bySize, order };
  }
  return null;
}

// Best-effort list of available color names from color-swatch UI (uses each
// swatch's alt/title/data-color, not concatenated text, to keep names clean).
export function colorsFromDom(doc) {
  const set = new Set();
  for (const scope of doc.querySelectorAll('[class*="color" i],[class*="colour" i],[class*="カラー"]')) {
    for (const e of scope.querySelectorAll("img,a,button,li,label,[data-color],[data-variation-color],[aria-label]")) {
      const v = (e.getAttribute("data-color") || e.getAttribute("data-variation-color") || e.getAttribute("title") || e.getAttribute("alt") || e.getAttribute("aria-label") || "").trim();
      if (v && v.length <= 20 && !/^https?:/.test(v) && !/^\d+$/.test(v) && !/選択|please|choose/i.test(v)) set.add(v);
    }
    if (set.size >= 2) break;
  }
  return [...set];
}

// Generic, site-agnostic extraction. Returns the full item shape.
export function extractGeneric(doc, loc) {
  const prods = jsonLdProducts(doc);
  const p = prods[0] || {};
  const offer = firstOffer(p) || {};

  let name = p.name || metaContent(doc, 'meta[property="og:title"]') || doc.title || "";
  if (typeof name === "object") name = name.name || "";

  let price = offer.price || offer.lowPrice ||
    metaContent(doc, 'meta[property="product:price:amount"]') ||
    metaContent(doc, 'meta[property="og:price:amount"]') || "";
  if (!price) price = pickPriceFromDom(doc);
  price = String(price).replace(/[^\d.]/g, "");

  const currency = offer.priceCurrency ||
    metaContent(doc, 'meta[property="product:price:currency"]') ||
    metaContent(doc, 'meta[property="og:price:currency"]') || "";

  let image = "";
  if (p.image) {
    const im = Array.isArray(p.image) ? p.image[0] : p.image;
    image = im && typeof im === "object" ? (im.url || im.contentUrl || "") : im;
  }
  if (!image) image = metaContent(doc, 'meta[property="og:image"]') ||
    metaContent(doc, 'meta[property="og:image:secure_url"]') ||
    metaContent(doc, 'meta[name="twitter:image"]') ||
    metaContent(doc, 'meta[name="twitter:image:src"]');
  if (!image) { const lp = doc.querySelector('link[rel="preload"][as="image"]'); if (lp) image = lp.getAttribute("href") || ""; }
  if (!image) image = biggestImage(doc);
  image = absUrl(image, loc.href); // relative / protocol-relative -> absolute

  let brand = "";
  if (p.brand) brand = typeof p.brand === "object" ? (p.brand.name || "") : p.brand;
  if (!brand) brand = metaContent(doc, 'meta[property="product:brand"]');

  const availability = normAvailability(
    offer.availability ||
    metaContent(doc, 'meta[property="product:availability"]') ||
    metaContent(doc, 'meta[property="og:availability"]') || ""
  );

  const table = measuresFromTable(doc);
  const measuresBySize = table ? table.bySize : {};

  // current color (what the user is viewing) + available color options
  let color = (typeof p.color === "string" ? p.color : "") ||
    metaContent(doc, 'meta[property="product:color"]') ||
    metaContent(doc, 'meta[property="og:color"]') || "";
  color = color.trim().slice(0, 40);
  const colorList = colorsFromDom(doc);
  const colors = colorList.join(", ");

  let sizes = sizesFromProduct(p);
  if (!sizes) sizes = sizesFromDom(doc);
  if (!sizes && table) sizes = table.order.join(", ");

  const url = loc.href;
  const domain = (loc.hostname || "").replace(/^www\./, "");
  const site = metaContent(doc, 'meta[property="og:site_name"]') || domainToSite(domain);

  // auto-classify from JSON-LD category / breadcrumb / product name
  let jsonldCat = "";
  if (p.category) jsonldCat = typeof p.category === "object" ? (p.category.name || "") : String(p.category);
  const guessed = guessCategory([name, jsonldCat, metaContent(doc, 'meta[property="product:category"]')].join(" "));

  return {
    url, domain, site, brand: brand || "",
    name: (name || "").trim().slice(0, 200),
    price, currency, image: image || "",
    availability, sizes, measuresBySize,
    color, colors,
    major: guessed.major, sub: guessed.sub,
  };
}

// ---- domain-rule layer (受け口) -----------------------------------------
//
// A rule is: { match, extract }
//   match:   string (exact domain), RegExp (tested against domain),
//            or (domain, loc) => boolean
//   extract: (doc, loc, base) => partial item  (only the keys it wants to
//            set). Any truthy value returned overrides the generic result,
//            so curated rules win on sites where structured data is wrong
//            or missing. Return {} to no-op.
//
// Rules let us bolt on per-site handling without touching the generic
// pass — the MVP ships with none, this is just the interface.

export function ruleMatches(rule, domain, loc) {
  const m = rule && rule.match;
  if (m == null) return false;
  if (typeof m === "string") return domain === m;
  if (m instanceof RegExp) return m.test(domain);
  if (typeof m === "function") return !!m(domain, loc);
  return false;
}

export function applyRules(base, doc, loc, rules) {
  if (!Array.isArray(rules) || !rules.length) return base;
  const domain = base.domain || "";
  const out = { ...base };
  for (const rule of rules) {
    if (!ruleMatches(rule, domain, loc)) continue;
    let partial;
    try { partial = rule.extract ? rule.extract(doc, loc, out) : null; } catch { partial = null; }
    if (partial && typeof partial === "object") {
      for (const k of Object.keys(partial)) {
        if (partial[k]) out[k] = partial[k];
      }
    }
    break; // first matching rule wins
  }
  return out;
}

// Top-level entry point used by the content script and the tests.
export function extractProduct(doc, loc, rules = []) {
  const base = extractGeneric(doc, loc);
  return applyRules(base, doc, loc, rules);
}

// @edit/extract — domain-specific rule registry (受け口).
//
// The MVP ships with an EMPTY list: the generic JSON-LD / OG / DOM pass
// covers most apparel & EC sites. This file is the seam for adding
// curated per-site handling later, without touching the generic
// extractor. Each entry is { match, extract } — see applyRules in
// index.js for the contract.
//
// Example (commented — do not enable without a fixture test):
//
//   {
//     match: "example-shop.jp",
//     extract: (doc, loc, base) => ({
//       price: (doc.querySelector(".product-price")?.textContent || "")
//         .replace(/[^\d.]/g, ""),
//     }),
//   },
//
// When you add a rule, add a matching fixture under test/fixtures/ and a
// case in test/extract.test.js so the rule stays honest.

export const DOMAIN_RULES = [];
